# Generated by Django 4.0.5 on 2022-10-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=125)),
                ('status', models.CharField(max_length=125)),
            ],
        ),
    ]
